### PR TITLE
Fix unsafe uses of referrer 'path'

### PR DESCRIPTION
**Pull request by nmielnik**
It's not safe to assume all referrer's will have a path.  There may be a better way to fix this at a high level (like when we parse the url) but this is the fix I'm currently using to workaround some errors.

### CODE REVIEW

**Comment by rybnik** [comment]
Hi @nmielnik great insight, although I must disagree with you, I believe that every object passed along to any matcher module is the product of a `url.parse` call and even if the `path` property is an empty string or a null object the `.path` property is still defined. Can you support any evidence that states otherwise?

Thank you for your time and consideration!

**Comment by rybnik** [comment]
No wait, I believe you might be right, because matchers call '.indexOf' on a possible `null`... let me give a second look at that :)

**Comment by nmielnik** [comment]
I saw this happening in our code when the referrer was `about:blank`  When node's url parse runs, it doesn't set a `path` property for this url.  I added a test case that should cover this, or you can just run node's `url.parse` on an `about` uri.

**Comment by rybnik** [comment]
Thank you @nmielnik and sorry about the huge delay, I'm not particularly fond of the current code aesthetics on the parsers section, but your code checks out and the tests run smoothly so I see no reason to keep this hanging.

**Comment by nmielnik** [comment]
Yeah, I can definitely see why it would be desirable to fix-up the parsers, as all those one-off if-statements aren't so hot.  Just wanted to get a fix in for the `about:` urls before anyone tries to make that look better.

**Pull request merged**
