### PR TITLE
Adding Korean search, email and social service sites.

### PR DESCRIPTION
**Pull request by xissy**
Adding Korean search, email and social service sites.
- Social
  - [me2day](http://me2day.net/)
- Search
  - [Naver](http://www.naver.com/)
  - [Daum](http://www.daum.net/)
  - [Nate](http://www.nate.com/)
- Email
  - [Naver Mail](http://mail.naver.com/)
  - [Daum Mail](http://mail.daum.net/)

### CODE REVIEW

**Comment by ivolo** [comment]
Thanks!

**Comment by xissy** [comment]
@ivolo Thanks too! Can you update this in NPM? It'll be more helpful to Korean developers.

**Comment by ivolo** [comment]
Done - 0.0.5! Thanks!

**Comment by xissy** [comment]
Thank you so much!

**Pull request merged**
